config/routes.rb
OpenIdConnectTestbed::Application.routes.draw do
  
  match 'sso/auth/openid_connect/callback' => 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'sessions#destroy', as: 'signout'

  resources :configs

end

app/models/omni_auth_config.rb
class OmniAuthConfig < ActiveRecord::Base

  def strategy_config
    strategy = Strategies.const_get(self.strategy, false)
    strategy.from_json(json)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def find_or_create_from_auth_hash(auth_hash)
    puts auth_hash.inspect
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    @configs = OmniAuthConfig.all
  end

  def edit
    @config = OmniAuthConfig.where(id: params[:id]).first
  end

  def update
    @config = OmniAuthConfig.update(params[:id], config_params)
    redirect_to edit_config_path(@config)
  end

  def config_params
    params.require(:omni_auth_config).permit(:json)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = @user
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/configs/edit.html.haml
= link_to "Configs Index", configs_path
= form_for @config, url: {action: "update"}, html: {class: "edit_config"} do |f|
  = f.text_area :json, size: "60x12", :class => "json_data"
  = f.submit "Save"

app/views/configs/index.html.haml
.configs
  - @configs.each do |config|
    .config
      = link_to config.strategy_config.name, edit_config_path(config)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenIdConnectTestbed</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>